### ISSUE TITLE
Bigrams in GSDMM model

### ISSUE THREAD

**Issue by khairiyah98** [bicachu/topic-modeling-health-tweets#1]
Hi, first of all, thank you for the great work!

May I know how I can include bigrams in the GSDMM model (instead of just unigrams)?

**Comment by bicachu** [comment]
Thanks! 

I believe you can pass in bigrams to the GSDMM model as a list of tokens just as you would for unigrams. If you need help generating the bigrams - I included a flag to enable this in the `clean_tweet` function in the  [clean_tokenizer.py ](https://github.com/bicachu/topic-modeling-health-tweets/blob/master/notebooks/clean_tokenizer.py). 

And [here](https://brittanybowers.com/a-unique-approach-to-short-text-clustering-part-2-tweets-spread-like-wildfire/) is someone's application of using bigrams with GSDMM found online.

**Comment by khairiyah98** [comment]
Thank you! That helped me a lot.

May I know if there are any topic coherence measures to determine the optimal number of topics (k) to use for the GSDMM model?

**Comment by bicachu** [comment]
GSDMM by default in theory is designed to find that optimal number of topics on it's own as long as you give it a large enough K value to serve as a ceiling. If you expect that your corpus has roughly 10 topics for instance, you may want to use a value higher than that (20). 
However, in practice whether or not it finds the best number of topics depends highly on the other hyperparameters (beta, alpha) as well as your underlying dataset. I wrote an [article about using the GSDMM model](https://medium.com/towards-artificial-intelligence/tweet-topic-modeling-part-3-using-short-text-topic-modeling-on-tweets-bc969a827fef) and talk briefly about choosing K in it if it helps.
